### ISSUE TITLE
Get VNC v1.4.0 working.

### ISSUE THREAD

**Issue by s0urce-c0de** [FinnBaltazar1111/desktoplite#1]

**Comment by s0urce-c0de** [comment]
I already had VNC v1.2.0 since long ago, I am experimenting with v1.4.0

**Comment by FinnBaltazar1111** [comment]
You don't need to create an issue for literally everything you need to tell me, just email me or tell me in person.

**Comment by FinnBaltazar1111** [comment]
You don't need to create an issue for everything GitHub related, just email me or tell me in person.

**Comment by s0urce-c0de** [comment]
ok
